# Configurações do Banco de Dados H2 (Modo Arquivo Persistente)
spring.datasource.url=jdbc:h2:file:./db/pantryguard;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configurações do Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar Console do H2 (útil para depuração)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Porta do Servidor
server.port=8080

# Configurações do Spring Mail (SMTP Mailtrap Sandbox)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=seu_usuario_mailtrap
spring.mail.password=sua_senha_mailtrap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configurações do Twilio WhatsApp API
twilio.account.sid=seu_account_sid_twilio
twilio.auth.token=seu_auth_token_twilio
twilio.whatsapp.number=whatsapp:+14155238886
twilio.recipient.number=whatsapp:+5511999999999

# Configurações do Firebase Cloud Messaging
firebase.config.path=classpath:serviceAccountKey.json

